package model;
// Generated 17-may-2018 18:48:50 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Employee generated by hbm2java
 */
public class Employee  implements java.io.Serializable {


     private Integer id;
     private String dni;
     private String name;
     private String surname;
     private String email;
     private String phone;
     private String rol;
     private String password;
     transient private Set requests = new HashSet(0);

    public Employee() {
    }

	
    public Employee(String dni, String name, String surname, String email, String phone, String rol, String password) {
        this.dni = dni;
        this.name = name;
        this.surname = surname;
        this.email = email;
        this.phone = phone;
        this.rol = rol;
        this.password = password;
    }
    public Employee(String dni, String name, String surname, String email, String phone, String rol, String password, Set requests) {
       this.dni = dni;
       this.name = name;
       this.surname = surname;
       this.email = email;
       this.phone = phone;
       this.rol = rol;
       this.password = password;
       this.requests = requests;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getRol() {
        return this.rol;
    }
    
    public void setRol(String rol) {
        this.rol = rol;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set getRequests() {
        return this.requests;
    }
    
    public void setRequests(Set requests) {
        this.requests = requests;
    }

    @Override
    public String toString() {
        return "Employee{" + "id=" + id + ", dni=" + dni + ", name=" + name + ", surname=" + surname + ", email=" + email + ", phone=" + phone + ", rol=" + rol + ", password=" + password + '}';
    }




}


