package model;
// Generated 17-may-2018 18:48:50 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Order generated by hbm2java
 */
public class Order  implements java.io.Serializable {


     private int id;
     private Budget budget;
     private Date date;
     private Date time;
     private String dniClient;
     private String country;
     private String city;
     private String province;
     private String town;
     private String cp;
     private String number;
     private String stairs;
     private String floor;
     private String door;

    public Order() {
    }

    public Order(int id, Budget budget, Date date, Date time, String dniClient, String country, String city, String province, String town, String cp, String number, String stairs, String floor, String door) {
       this.id = id;
       this.budget = budget;
       this.date = date;
       this.time = time;
       this.dniClient = dniClient;
       this.country = country;
       this.city = city;
       this.province = province;
       this.town = town;
       this.cp = cp;
       this.number = number;
       this.stairs = stairs;
       this.floor = floor;
       this.door = door;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Budget getBudget() {
        return this.budget;
    }
    
    public void setBudget(Budget budget) {
        this.budget = budget;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }
    public String getDniClient() {
        return this.dniClient;
    }
    
    public void setDniClient(String dniClient) {
        this.dniClient = dniClient;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getProvince() {
        return this.province;
    }
    
    public void setProvince(String province) {
        this.province = province;
    }
    public String getTown() {
        return this.town;
    }
    
    public void setTown(String town) {
        this.town = town;
    }
    public String getCp() {
        return this.cp;
    }
    
    public void setCp(String cp) {
        this.cp = cp;
    }
    public String getNumber() {
        return this.number;
    }
    
    public void setNumber(String number) {
        this.number = number;
    }
    public String getStairs() {
        return this.stairs;
    }
    
    public void setStairs(String stairs) {
        this.stairs = stairs;
    }
    public String getFloor() {
        return this.floor;
    }
    
    public void setFloor(String floor) {
        this.floor = floor;
    }
    public String getDoor() {
        return this.door;
    }
    
    public void setDoor(String door) {
        this.door = door;
    }




}


