package model;
// Generated 17-may-2018 18:48:50 by Hibernate Tools 4.3.1



/**
 * Photos generated by hbm2java
 */
public class Photos  implements java.io.Serializable {


     private Integer id;
     private Request request;
     private String path;

    public Photos() {
    }

    public Photos(Request request, String path) {
       this.request = request;
       this.path = path;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Request getRequest() {
        return this.request;
    }
    
    public void setRequest(Request request) {
        this.request = request;
    }
    public String getPath() {
        return this.path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }




}


