package model;
// Generated 17-may-2018 18:48:50 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Request generated by hbm2java
 */
public class Request  implements java.io.Serializable {


     private Integer id;
     private Client client;
     private Employee employee;
     private Date date;
     private Date time;
     private boolean finished;
     private Set photoses = new HashSet(0);
     private Set budgets = new HashSet(0);

    public Request() {
    }

	
    public Request(Client client, Employee employee, Date date, Date time, boolean finished) {
        this.client = client;
        this.employee = employee;
        this.date = date;
        this.time = time;
        this.finished = finished;
    }
    public Request(Client client, Employee employee, Date date, Date time, boolean finished, Set photoses, Set budgets) {
       this.client = client;
       this.employee = employee;
       this.date = date;
       this.time = time;
       this.finished = finished;
       this.photoses = photoses;
       this.budgets = budgets;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }
    public boolean isFinished() {
        return this.finished;
    }
    
    public void setFinished(boolean finished) {
        this.finished = finished;
    }
    public Set getPhotoses() {
        return this.photoses;
    }
    
    public void setPhotoses(Set photoses) {
        this.photoses = photoses;
    }
    public Set getBudgets() {
        return this.budgets;
    }
    
    public void setBudgets(Set budgets) {
        this.budgets = budgets;
    }




}


